// Detailed information for key elements
export const detailedElementsData = {
  1: {
    atomicMass: '1.008',
    electronConfiguration: '1s¹',
    discoveryYear: 1766,
    discoveredBy: 'Henry Cavendish',
    discoveryHistory: 'Hydrogen was first recognized as a distinct element by Henry Cavendish in 1766. The name comes from the Greek words "hydro" (water) and "genes" (forming), meaning water-forming.',
    physicalProperties: {
      meltingPoint: '-259.14°C',
      boilingPoint: '-252.87°C',
      density: '0.0899 g/L',
      state: 'Gas',
      appearance: 'Colorless gas',
      atomicRadius: '53 pm',
    },
    chemicalProperties: {
      electronegativity: '2.20',
      ionizationEnergy: '1312 kJ/mol',
      oxidationStates: '-1, +1',
      valence: '1',
    },
    commonCompounds: ['H₂O (Water)', 'H₂SO₄ (Sulfuric acid)', 'HCl (Hydrochloric acid)', 'NH₃ (Ammonia)', 'CH₄ (Methane)'],
    applications: ['Fuel for rockets and vehicles', 'Production of ammonia for fertilizers', 'Hydrogenation of fats and oils', 'Welding and metal cutting'],
    biologicalRole: 'Essential component of water and organic compounds in all living organisms.',
    interestingFacts: ['Most abundant element in the universe', 'The sun is primarily composed of hydrogen', 'Used in fuel cells for clean energy'],
  },
  2: {
    atomicMass: '4.003',
    electronConfiguration: '1s²',
    discoveryYear: 1868,
    discoveredBy: 'Pierre Janssen, Norman Lockyer',
    discoveryHistory: 'Helium was first detected in the sun\'s spectrum during a solar eclipse in 1868. Named after Helios, the Greek god of the sun.',
    physicalProperties: { meltingPoint: 'N/A', boilingPoint: '-268.93°C', density: '0.1785 g/L', state: 'Gas', appearance: 'Colorless gas', atomicRadius: '31 pm' },
    chemicalProperties: { electronegativity: 'N/A', ionizationEnergy: '2372 kJ/mol', oxidationStates: '0', valence: '0' },
    commonCompounds: ['He (Monoatomic - does not form stable compounds)'],
    applications: ['Balloons and airships', 'Cryogenics and superconducting magnets', 'Diving gas mixtures', 'MRI scanners'],
    biologicalRole: 'Biologically inert with no known biological role.',
    interestingFacts: ['Second most abundant element in the universe', 'Only element discovered in space before Earth', 'Cannot be liquefied by pressure alone'],
  },
  6: {
    atomicMass: '12.011',
    electronConfiguration: '[He] 2s² 2p²',
    discoveryYear: 'Ancient',
    discoveredBy: 'Known since ancient times',
    discoveryHistory: 'Carbon has been known since ancient times in the form of charcoal and soot. The name comes from Latin "carbo" meaning coal.',
    physicalProperties: { meltingPoint: '3550°C', boilingPoint: '4027°C', density: '2.267 g/cm³', state: 'Solid', appearance: 'Black (graphite) or transparent (diamond)', atomicRadius: '67 pm' },
    chemicalProperties: { electronegativity: '2.55', ionizationEnergy: '1086 kJ/mol', oxidationStates: '-4 to +4', valence: '4' },
    commonCompounds: ['CO₂ (Carbon dioxide)', 'CO (Carbon monoxide)', 'CH₄ (Methane)', 'Organic compounds'],
    applications: ['Steel production', 'Plastics and synthetic materials', 'Fuel sources', 'Carbon fiber composites', 'Electronics'],
    biologicalRole: 'Fundamental building block of all known life.',
    interestingFacts: ['Forms more compounds than any other element', 'Diamond is the hardest natural material', 'Graphite is very soft'],
  },
  7: {
    atomicMass: '14.007',
    electronConfiguration: '[He] 2s² 2p³',
    discoveryYear: 1772,
    discoveredBy: 'Daniel Rutherford',
    discoveryHistory: 'Nitrogen was discovered by Daniel Rutherford in 1772. The name comes from Greek "nitron genes" meaning "niter forming".',
    physicalProperties: { meltingPoint: '-210.00°C', boilingPoint: '-195.79°C', density: '1.251 g/L', state: 'Gas', appearance: 'Colorless gas', atomicRadius: '56 pm' },
    chemicalProperties: { electronegativity: '3.04', ionizationEnergy: '1402 kJ/mol', oxidationStates: '-3 to +5', valence: '3, 5' },
    commonCompounds: ['NH₃ (Ammonia)', 'HNO₃ (Nitric acid)', 'N₂O (Nitrous oxide)', 'Proteins and DNA'],
    applications: ['Fertilizer production', 'Explosives', 'Food preservation', 'Cryogenic applications'],
    biologicalRole: 'Essential component of amino acids, proteins, and nucleic acids.',
    interestingFacts: ['Makes up 78% of Earth\'s atmosphere', 'Relatively inert at room temperature', 'Critical for the nitrogen cycle'],
  },
  8: {
    atomicMass: '15.999',
    electronConfiguration: '[He] 2s² 2p⁴',
    discoveryYear: 1774,
    discoveredBy: 'Joseph Priestley, Carl Wilhelm Scheele',
    discoveryHistory: 'Oxygen was independently discovered by Joseph Priestley in 1774 and Carl Wilhelm Scheele. Named "oxygen" from Greek "oxys genes" meaning "acid former".',
    physicalProperties: { meltingPoint: '-218.79°C', boilingPoint: '-182.96°C', density: '1.429 g/L', state: 'Gas', appearance: 'Colorless gas', atomicRadius: '48 pm' },
    chemicalProperties: { electronegativity: '3.44', ionizationEnergy: '1314 kJ/mol', oxidationStates: '-2, -1', valence: '2' },
    commonCompounds: ['H₂O (Water)', 'O₂ (Dioxygen)', 'O₃ (Ozone)', 'CO₂ (Carbon dioxide)', 'Metal oxides'],
    applications: ['Respiration and life support', 'Steel manufacturing', 'Water treatment', 'Medical oxygen therapy', 'Rocket propellant'],
    biologicalRole: 'Essential for cellular respiration in most living organisms.',
    interestingFacts: ['Most abundant element in Earth\'s crust', 'Supports combustion', 'Ozone layer protects from UV radiation'],
  },
  11: {
    atomicMass: '22.990',
    electronConfiguration: '[Ne] 3s¹',
    discoveryYear: 1807,
    discoveredBy: 'Humphry Davy',
    discoveryHistory: 'Sodium was isolated by Humphry Davy in 1807 through electrolysis of caustic soda. Named from Medieval Latin "sodanum".',
    physicalProperties: { meltingPoint: '97.72°C', boilingPoint: '883°C', density: '0.971 g/cm³', state: 'Solid', appearance: 'Soft silvery-white metal', atomicRadius: '186 pm' },
    chemicalProperties: { electronegativity: '0.93', ionizationEnergy: '496 kJ/mol', oxidationStates: '+1', valence: '1' },
    commonCompounds: ['NaCl (Table salt)', 'NaOH (Sodium hydroxide)', 'NaHCO₃ (Baking soda)', 'Na₂CO₃ (Soda ash)'],
    applications: ['Salt production', 'Sodium vapor lamps', 'Chemical synthesis', 'Coolant in nuclear reactors', 'Soap production'],
    biologicalRole: 'Essential for nerve transmission and cellular fluid balance.',
    interestingFacts: ['Highly reactive with water', 'Must be stored in oil', 'Sixth most abundant element in Earth\'s crust'],
  },
  17: {
    atomicMass: '35.453',
    electronConfiguration: '[Ne] 3s² 3p⁵',
    discoveryYear: 1774,
    discoveredBy: 'Carl Wilhelm Scheele',
    discoveryHistory: 'Discovered by Carl Wilhelm Scheele in 1774. Named from Greek "chloros" meaning pale green.',
    physicalProperties: { meltingPoint: '-101.5°C', boilingPoint: '-34.04°C', density: '3.214 g/L', state: 'Gas', appearance: 'Yellow-green gas', atomicRadius: '79 pm' },
    chemicalProperties: { electronegativity: '3.16', ionizationEnergy: '1251 kJ/mol', oxidationStates: '-1 to +7', valence: '1, 3, 5, 7' },
    commonCompounds: ['NaCl (Table salt)', 'HCl (Hydrochloric acid)', 'NaClO (Bleach)', 'PVC (Polyvinyl chloride)'],
    applications: ['Water purification', 'Production of plastics', 'Bleaching agent', 'Chemical synthesis', 'Swimming pool treatment'],
    biologicalRole: 'Essential electrolyte for fluid balance and nerve function.',
    interestingFacts: ['Used as chemical weapon in WWI', 'Strong oxidizing agent', 'Characteristic pungent smell'],
  },
  26: {
    atomicMass: '55.845',
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    discoveryYear: 'Ancient',
    discoveredBy: 'Known since ancient times',
    discoveryHistory: 'Iron has been known and used since prehistoric times. The Iron Age began around 1200 BCE. Name from Anglo-Saxon "iren".',
    physicalProperties: { meltingPoint: '1538°C', boilingPoint: '2862°C', density: '7.874 g/cm³', state: 'Solid', appearance: 'Lustrous metallic gray', atomicRadius: '126 pm' },
    chemicalProperties: { electronegativity: '1.83', ionizationEnergy: '762 kJ/mol', oxidationStates: '+2, +3', valence: '2, 3' },
    commonCompounds: ['Fe₂O₃ (Iron(III) oxide/rust)', 'FeO (Iron(II) oxide)', 'Fe₃O₄ (Magnetite)', 'FeSO₄ (Iron(II) sulfate)'],
    applications: ['Steel production', 'Construction', 'Tools and machinery', 'Transportation', 'Hemoglobin in blood'],
    biologicalRole: 'Essential for oxygen transport in blood and many enzymatic processes.',
    interestingFacts: ['Most abundant element on Earth by mass', 'Earth\'s core is primarily iron', 'Can be magnetized', 'Rusts when exposed to oxygen and moisture'],
  },
  29: {
    atomicMass: '63.546',
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    discoveryYear: 'Ancient',
    discoveredBy: 'Known since ancient times',
    discoveryHistory: 'One of the first metals worked by humans (9000 BCE). Named from Latin "cuprum" from Cyprus.',
    physicalProperties: { meltingPoint: '1084.62°C', boilingPoint: '2562°C', density: '8.96 g/cm³', state: 'Solid', appearance: 'Reddish-orange metallic', atomicRadius: '128 pm' },
    chemicalProperties: { electronegativity: '1.90', ionizationEnergy: '745 kJ/mol', oxidationStates: '+1, +2', valence: '1, 2' },
    commonCompounds: ['CuO (Copper(II) oxide)', 'Cu₂O (Copper(I) oxide)', 'CuSO₄ (Copper sulfate)', 'CuCl₂ (Copper(II) chloride)'],
    applications: ['Electrical wiring', 'Plumbing', 'Heat exchangers', 'Coins', 'Antibacterial surfaces'],
    biologicalRole: 'Essential trace element for enzyme function.',
    interestingFacts: ['Excellent conductor of electricity', 'Develops green patina', 'Has natural antimicrobial properties'],
  },
  47: {
    atomicMass: '107.868',
    electronConfiguration: '[Kr] 4d¹⁰ 5s¹',
    discoveryYear: 'Ancient',
    discoveredBy: 'Known since ancient times',
    discoveryHistory: 'Known since ancient times (3000 BCE). Name from Anglo-Saxon "seolfor". Symbol Ag from Latin "argentum".',
    physicalProperties: { meltingPoint: '961.78°C', boilingPoint: '2162°C', density: '10.501 g/cm³', state: 'Solid', appearance: 'Lustrous white metallic', atomicRadius: '144 pm' },
    chemicalProperties: { electronegativity: '1.93', ionizationEnergy: '731 kJ/mol', oxidationStates: '+1, +2', valence: '1' },
    commonCompounds: ['AgNO₃ (Silver nitrate)', 'AgCl (Silver chloride)', 'Ag₂O (Silver oxide)', 'Ag₂S (Tarnish)'],
    applications: ['Jewelry', 'Photography', 'Electrical contacts', 'Antibacterial coatings', 'Solar panels'],
    biologicalRole: 'Not essential; has antimicrobial properties.',
    interestingFacts: ['Best conductor of electricity and heat', 'Highly reflective', 'Tarnishes in presence of sulfur'],
  },
  79: {
    atomicMass: '196.967',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    discoveryYear: 'Ancient',
    discoveredBy: 'Known since ancient times',
    discoveryHistory: 'Treasured since prehistoric times (4000 BCE). Name from Anglo-Saxon "gold". Symbol Au from Latin "aurum".',
    physicalProperties: { meltingPoint: '1064.18°C', boilingPoint: '2856°C', density: '19.282 g/cm³', state: 'Solid', appearance: 'Bright yellow metallic', atomicRadius: '144 pm' },
    chemicalProperties: { electronegativity: '2.54', ionizationEnergy: '890 kJ/mol', oxidationStates: '+1, +3', valence: '1, 3' },
    commonCompounds: ['AuCl₃ (Gold(III) chloride)', 'HAuCl₄ (Chloroauric acid)', 'Colloidal gold'],
    applications: ['Jewelry', 'Financial reserves', 'Electronics', 'Medical applications', 'Aerospace technology'],
    biologicalRole: 'Not essential; used in some medical treatments.',
    interestingFacts: ['Most malleable and ductile metal', 'Does not tarnish or corrode', 'Can be beaten into extremely thin sheets'],
  },
};
