// Basic element data for periodic table grid positioning
export const elementsBasicData = [
  // Period 1
  { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', category: 'nonmetal', group: 1, period: 1 },
  { atomicNumber: 2, symbol: 'He', name: 'Helium', category: 'noble gas', group: 18, period: 1 },
  
  // Period 2
  { atomicNumber: 3, symbol: 'Li', name: 'Lithium', category: 'alkali metal', group: 1, period: 2 },
  { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', category: 'alkaline earth metal', group: 2, period: 2 },
  { atomicNumber: 5, symbol: 'B', name: 'Boron', category: 'metalloid', group: 13, period: 2 },
  { atomicNumber: 6, symbol: 'C', name: 'Carbon', category: 'nonmetal', group: 14, period: 2 },
  { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', category: 'nonmetal', group: 15, period: 2 },
  { atomicNumber: 8, symbol: 'O', name: 'Oxygen', category: 'nonmetal', group: 16, period: 2 },
  { atomicNumber: 9, symbol: 'F', name: 'Fluorine', category: 'halogen', group: 17, period: 2 },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon', category: 'noble gas', group: 18, period: 2 },
  
  // Period 3
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium', category: 'alkali metal', group: 1, period: 3 },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', category: 'alkaline earth metal', group: 2, period: 3 },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminum', category: 'post-transition metal', group: 13, period: 3 },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon', category: 'metalloid', group: 14, period: 3 },
  { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', category: 'nonmetal', group: 15, period: 3 },
  { atomicNumber: 16, symbol: 'S', name: 'Sulfur', category: 'nonmetal', group: 16, period: 3 },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', category: 'halogen', group: 17, period: 3 },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon', category: 'noble gas', group: 18, period: 3 },
  
  // Period 4
  { atomicNumber: 19, symbol: 'K', name: 'Potassium', category: 'alkali metal', group: 1, period: 4 },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', category: 'alkaline earth metal', group: 2, period: 4 },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', category: 'transition metal', group: 3, period: 4 },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', category: 'transition metal', group: 4, period: 4 },
  { atomicNumber: 23, symbol: 'V', name: 'Vanadium', category: 'transition metal', group: 5, period: 4 },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', category: 'transition metal', group: 6, period: 4 },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', category: 'transition metal', group: 7, period: 4 },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron', category: 'transition metal', group: 8, period: 4 },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', category: 'transition metal', group: 9, period: 4 },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', category: 'transition metal', group: 10, period: 4 },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper', category: 'transition metal', group: 11, period: 4 },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', category: 'transition metal', group: 12, period: 4 },
  { atomicNumber: 31, symbol: 'Ga', name: 'Gallium', category: 'post-transition metal', group: 13, period: 4 },
  { atomicNumber: 32, symbol: 'Ge', name: 'Germanium', category: 'metalloid', group: 14, period: 4 },
  { atomicNumber: 33, symbol: 'As', name: 'Arsenic', category: 'metalloid', group: 15, period: 4 },
  { atomicNumber: 34, symbol: 'Se', name: 'Selenium', category: 'nonmetal', group: 16, period: 4 },
  { atomicNumber: 35, symbol: 'Br', name: 'Bromine', category: 'halogen', group: 17, period: 4 },
  { atomicNumber: 36, symbol: 'Kr', name: 'Krypton', category: 'noble gas', group: 18, period: 4 },
  
  // Period 5
  { atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', category: 'alkali metal', group: 1, period: 5 },
  { atomicNumber: 38, symbol: 'Sr', name: 'Strontium', category: 'alkaline earth metal', group: 2, period: 5 },
  { atomicNumber: 39, symbol: 'Y', name: 'Yttrium', category: 'transition metal', group: 3, period: 5 },
  { atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', category: 'transition metal', group: 4, period: 5 },
  { atomicNumber: 41, symbol: 'Nb', name: 'Niobium', category: 'transition metal', group: 5, period: 5 },
  { atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', category: 'transition metal', group: 6, period: 5 },
  { atomicNumber: 43, symbol: 'Tc', name: 'Technetium', category: 'transition metal', group: 7, period: 5 },
  { atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', category: 'transition metal', group: 8, period: 5 },
  { atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', category: 'transition metal', group: 9, period: 5 },
  { atomicNumber: 46, symbol: 'Pd', name: 'Palladium', category: 'transition metal', group: 10, period: 5 },
  { atomicNumber: 47, symbol: 'Ag', name: 'Silver', category: 'transition metal', group: 11, period: 5 },
  { atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', category: 'transition metal', group: 12, period: 5 },
  { atomicNumber: 49, symbol: 'In', name: 'Indium', category: 'post-transition metal', group: 13, period: 5 },
  { atomicNumber: 50, symbol: 'Sn', name: 'Tin', category: 'post-transition metal', group: 14, period: 5 },
  { atomicNumber: 51, symbol: 'Sb', name: 'Antimony', category: 'metalloid', group: 15, period: 5 },
  { atomicNumber: 52, symbol: 'Te', name: 'Tellurium', category: 'metalloid', group: 16, period: 5 },
  { atomicNumber: 53, symbol: 'I', name: 'Iodine', category: 'halogen', group: 17, period: 5 },
  { atomicNumber: 54, symbol: 'Xe', name: 'Xenon', category: 'noble gas', group: 18, period: 5 },
  
  // Period 6
  { atomicNumber: 55, symbol: 'Cs', name: 'Cesium', category: 'alkali metal', group: 1, period: 6 },
  { atomicNumber: 56, symbol: 'Ba', name: 'Barium', category: 'alkaline earth metal', group: 2, period: 6 },
  { atomicNumber: 57, symbol: 'La', name: 'Lanthanum', category: 'lanthanide', group: 3, period: 6 },
  { atomicNumber: 72, symbol: 'Hf', name: 'Hafnium', category: 'transition metal', group: 4, period: 6 },
  { atomicNumber: 73, symbol: 'Ta', name: 'Tantalum', category: 'transition metal', group: 5, period: 6 },
  { atomicNumber: 74, symbol: 'W', name: 'Tungsten', category: 'transition metal', group: 6, period: 6 },
  { atomicNumber: 75, symbol: 'Re', name: 'Rhenium', category: 'transition metal', group: 7, period: 6 },
  { atomicNumber: 76, symbol: 'Os', name: 'Osmium', category: 'transition metal', group: 8, period: 6 },
  { atomicNumber: 77, symbol: 'Ir', name: 'Iridium', category: 'transition metal', group: 9, period: 6 },
  { atomicNumber: 78, symbol: 'Pt', name: 'Platinum', category: 'transition metal', group: 10, period: 6 },
  { atomicNumber: 79, symbol: 'Au', name: 'Gold', category: 'transition metal', group: 11, period: 6 },
  { atomicNumber: 80, symbol: 'Hg', name: 'Mercury', category: 'transition metal', group: 12, period: 6 },
  { atomicNumber: 81, symbol: 'Tl', name: 'Thallium', category: 'post-transition metal', group: 13, period: 6 },
  { atomicNumber: 82, symbol: 'Pb', name: 'Lead', category: 'post-transition metal', group: 14, period: 6 },
  { atomicNumber: 83, symbol: 'Bi', name: 'Bismuth', category: 'post-transition metal', group: 15, period: 6 },
  { atomicNumber: 84, symbol: 'Po', name: 'Polonium', category: 'metalloid', group: 16, period: 6 },
  { atomicNumber: 85, symbol: 'At', name: 'Astatine', category: 'halogen', group: 17, period: 6 },
  { atomicNumber: 86, symbol: 'Rn', name: 'Radon', category: 'noble gas', group: 18, period: 6 },
  
  // Period 7
  { atomicNumber: 87, symbol: 'Fr', name: 'Francium', category: 'alkali metal', group: 1, period: 7 },
  { atomicNumber: 88, symbol: 'Ra', name: 'Radium', category: 'alkaline earth metal', group: 2, period: 7 },
  { atomicNumber: 89, symbol: 'Ac', name: 'Actinium', category: 'actinide', group: 3, period: 7 },
  { atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', category: 'transition metal', group: 4, period: 7 },
  { atomicNumber: 105, symbol: 'Db', name: 'Dubnium', category: 'transition metal', group: 5, period: 7 },
  { atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium', category: 'transition metal', group: 6, period: 7 },
  { atomicNumber: 107, symbol: 'Bh', name: 'Bohrium', category: 'transition metal', group: 7, period: 7 },
  { atomicNumber: 108, symbol: 'Hs', name: 'Hassium', category: 'transition metal', group: 8, period: 7 },
  { atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium', category: 'transition metal', group: 9, period: 7 },
  { atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', category: 'transition metal', group: 10, period: 7 },
  { atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium', category: 'transition metal', group: 11, period: 7 },
  { atomicNumber: 112, symbol: 'Cn', name: 'Copernicium', category: 'transition metal', group: 12, period: 7 },
  { atomicNumber: 113, symbol: 'Nh', name: 'Nihonium', category: 'post-transition metal', group: 13, period: 7 },
  { atomicNumber: 114, symbol: 'Fl', name: 'Flerovium', category: 'post-transition metal', group: 14, period: 7 },
  { atomicNumber: 115, symbol: 'Mc', name: 'Moscovium', category: 'post-transition metal', group: 15, period: 7 },
  { atomicNumber: 116, symbol: 'Lv', name: 'Livermorium', category: 'post-transition metal', group: 16, period: 7 },
  { atomicNumber: 117, symbol: 'Ts', name: 'Tennessine', category: 'halogen', group: 17, period: 7 },
  { atomicNumber: 118, symbol: 'Og', name: 'Oganesson', category: 'noble gas', group: 18, period: 7 },
  
  // Lanthanides
  { atomicNumber: 58, symbol: 'Ce', name: 'Cerium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 60, symbol: 'Nd', name: 'Neodymium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 61, symbol: 'Pm', name: 'Promethium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 62, symbol: 'Sm', name: 'Samarium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 63, symbol: 'Eu', name: 'Europium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 65, symbol: 'Tb', name: 'Terbium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 67, symbol: 'Ho', name: 'Holmium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 68, symbol: 'Er', name: 'Erbium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 69, symbol: 'Tm', name: 'Thulium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium', category: 'lanthanide', group: 0, period: 8.5 },
  { atomicNumber: 71, symbol: 'Lu', name: 'Lutetium', category: 'lanthanide', group: 0, period: 8.5 },
  
  // Actinides
  { atomicNumber: 90, symbol: 'Th', name: 'Thorium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 91, symbol: 'Pa', name: 'Protactinium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 92, symbol: 'U', name: 'Uranium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 93, symbol: 'Np', name: 'Neptunium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 94, symbol: 'Pu', name: 'Plutonium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 95, symbol: 'Am', name: 'Americium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 96, symbol: 'Cm', name: 'Curium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 97, symbol: 'Bk', name: 'Berkelium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 98, symbol: 'Cf', name: 'Californium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 99, symbol: 'Es', name: 'Einsteinium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 100, symbol: 'Fm', name: 'Fermium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 101, symbol: 'Md', name: 'Mendelevium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 102, symbol: 'No', name: 'Nobelium', category: 'actinide', group: 0, period: 9.5 },
  { atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium', category: 'actinide', group: 0, period: 9.5 },
];

export const categoryColors = {
  'nonmetal': '#FFE082',
  'noble gas': '#C5CAE9',
  'alkali metal': '#EF9A9A',
  'alkaline earth metal': '#FFCC80',
  'metalloid': '#BCAAA4',
  'halogen': '#FFF59D',
  'transition metal': '#FFB74D',
  'post-transition metal': '#90CAF9',
  'lanthanide': '#CE93D8',
  'actinide': '#F48FB1',
};
