// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class Class
{
    public int Id { get; set; }

    public string ClassName { get; set; }

    public int GradeLevel { get; set; }

    public string AcademicYear { get; set; }

    public int? CreatedByTeacher { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ClassEnrollment> ClassEnrollments { get; set; } = new List<ClassEnrollment>();

    public virtual ICollection<ClassSlot> ClassSlots { get; set; } = new List<ClassSlot>();

    public virtual Teacher CreatedByTeacherNavigation { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}