// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class ExamAttemptAnswer
{
    public int Id { get; set; }

    public int ExamAttemptId { get; set; }

    public int QuestionId { get; set; }

    public List<int> SelectedAnswerIds { get; set; }

    public string TextAnswer { get; set; }

    public string AnswerData { get; set; }

    public decimal? PointsEarned { get; set; }

    public decimal? PointsPossible { get; set; }

    public bool? IsCorrect { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ExamAttempt ExamAttempt { get; set; }

    public virtual Question Question { get; set; }
}