// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LessonPlanExam.Repositories.Enums;

namespace LessonPlanExam.Repositories.Models;

public partial class ExamAttempt
{
    public int Id { get; set; }

    public int ExamId { get; set; }

    public int StudentId { get; set; }

    public int AttemptNumber { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public int? TimeSpentSeconds { get; set; }

    public decimal? TotalScore { get; set; }

    public decimal? MaxScore { get; set; }

    public decimal? ScorePercentage { get; set; }

    public EAttemptStatus? StatusEnum { get; set; }

    public DateTime? AutoGradedAt { get; set; }

    public DateTime? ManualGradedAt { get; set; }

    public int? GradedBy { get; set; }

    public string Feedback { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ICollection<ExamAttemptAnswer> ExamAttemptAnswers { get; set; } = new List<ExamAttemptAnswer>();

    public virtual Teacher GradedByNavigation { get; set; }

    public virtual Student Student { get; set; }
}