// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LessonPlanExam.Repositories.Enums;

namespace LessonPlanExam.Repositories.Models;

public partial class Exam
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CreatedByTeacher { get; set; }

    public int? ExamMatrixId { get; set; }

    public int? GradeLevel { get; set; }

    public string Description { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int DurationMinutes { get; set; }

    public string PasswordHash { get; set; }

    public int? MaxAttempts { get; set; }

    public EScoringMethod? ScoringMethodEnum { get; set; }

    public bool? ShowResultsImmediately { get; set; }

    public bool? ShowCorrectAnswers { get; set; }

    public bool? RandomizeQuestions { get; set; }

    public bool? RandomizeAnswers { get; set; }

    public EExamStatus? StatusEnum { get; set; }

    public int? TotalQuestions { get; set; }

    public decimal? TotalPoints { get; set; }

    public decimal? PassThreshold { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Teacher CreatedByTeacherNavigation { get; set; }

    public virtual ICollection<ExamAttempt> ExamAttempts { get; set; } = new List<ExamAttempt>();

    public virtual ExamMatrix ExamMatrix { get; set; }

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();
}