// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class ExamMatrix
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TeacherId { get; set; }

    public string Description { get; set; }

    public int? TotalQuestions { get; set; }

    public decimal? TotalPoints { get; set; }

    public string Configuration { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ExamMatrixItem> ExamMatrixItems { get; set; } = new List<ExamMatrixItem>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual Teacher Teacher { get; set; }
}