// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class ExamQuestion
{
    public int Id { get; set; }

    public int ExamId { get; set; }

    public int QuestionId { get; set; }

    public int OrderIndex { get; set; }

    public decimal? Points { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question Question { get; set; }
}