// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class ExamMatrixItem
{
    public int Id { get; set; }

    public int ExamMatrixId { get; set; }

    public int QuestionBankId { get; set; }

    public string Domain { get; set; }

    public int? DifficultyLevel { get; set; }

    public int QuestionCount { get; set; }

    public decimal? PointsPerQuestion { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ExamMatrix ExamMatrix { get; set; }

    public virtual QuestionBank QuestionBank { get; set; }
}