// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class LessonPlanFile
{
    public int Id { get; set; }

    public int LessonPlanId { get; set; }

    public string FileUrl { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual LessonPlan LessonPlan { get; set; }
}