// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class LessonPlan
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CreatedByTeacher { get; set; }

    public string Objectives { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public string ImageUrl { get; set; }

    public int GradeLevel { get; set; }

    public virtual Teacher CreatedByTeacherNavigation { get; set; }

    public virtual ICollection<SlotPlan> SlotPlans { get; set; } = new List<SlotPlan>();
}