// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LessonPlanExam.Repositories.Enums;

namespace LessonPlanExam.Repositories.Models;

public partial class Question
{
    public int Id { get; set; }

    public int QuestionBankId { get; set; }

    public int? QuestionDifficultyId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public EQuestionType QuestionTypeEnum { get; set; }

    public string AdditionalData { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ExamAttemptAnswer> ExamAttemptAnswers { get; set; } = new List<ExamAttemptAnswer>();

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual QuestionBank QuestionBank { get; set; }

    public virtual QuestionDifficulty QuestionDifficulty { get; set; }

    public virtual ICollection<QuestionFillBlankAnswer> QuestionFillBlankAnswers { get; set; } = new List<QuestionFillBlankAnswer>();

    public virtual ICollection<QuestionMultipleChoiceAnswer> QuestionMultipleChoiceAnswers { get; set; } = new List<QuestionMultipleChoiceAnswer>();
}