// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class QuestionMultipleChoiceAnswer
{
    public int Id { get; set; }

    public int QuestionId { get; set; }

    public string AnswerText { get; set; }

    public bool? IsCorrect { get; set; }

    public string Explanation { get; set; }

    public int? OrderIndex { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Question Question { get; set; }
}