// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LessonPlanExam.Repositories.Enums;

namespace LessonPlanExam.Repositories.Models;

public partial class QuestionBank
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int GradeLevel { get; set; }

    public int TeacherId { get; set; }

    public string Description { get; set; }

    public EQuestionBankStatus? StatusEnum { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ExamMatrixItem> ExamMatrixItems { get; set; } = new List<ExamMatrixItem>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual Teacher Teacher { get; set; }
}