// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class SlotMaterial
{
    public int Id { get; set; }

    public int SlotPlanId { get; set; }

    public string Title { get; set; }

    public string Url { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual SlotPlan SlotPlan { get; set; }
}