// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LessonPlanExam.Repositories.Models;

public partial class SlotPlan
{
    public int Id { get; set; }

    public int LessonPlanId { get; set; }

    public int SlotNumber { get; set; }

    public string Title { get; set; }

    public int? DurationMinutes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Objectives { get; set; }

    public string EquipmentNeeded { get; set; }

    public string Preparations { get; set; }

    public string Activities { get; set; }

    public string ReviseQuestions { get; set; }

    public virtual LessonPlan LessonPlan { get; set; }

    public virtual ICollection<SlotMaterial> SlotMaterials { get; set; } = new List<SlotMaterial>();
}